---
- name: Install python docker
  become: true
  pip:
    name: "{{ item }}"
    virtualenv: /ansible/bin/python
    virtualenv_command: python3.9 -m venv
    virtualenv_site_packages: false

  loop:
    - docker
    - docker-compose
