---
- name: Install python docker
  become: true
  pip:
    name: "{{ item }}"
    virtualenv: /ansible
    virtualenv_command: "python -m venv"
    virtualenv_site_packages: false
  loop:
    - docker
    - docker-compose

- set_fact:
    ansible_python_interpreter: /ansible/bin/python
