---
- name: Create authelia dir
  ansible.builtin.file:
    path: "{{ traefik_authelia_dir }}"
    state: directory
    mode: '0700'
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"

- name: Copy users_database file
  ansible.builtin.template:
    src: "users_database.yml.j2"
    dest: "{{ traefik_authelia_dir }}/users_database.yml"
    mode: '0644'
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"

- name: Copy authelia template file
  ansible.builtin.template:
    src: "authelia.yml.j2"
    dest: "{{ traefik_authelia_dir }}/configuration.yml"
    mode: '0644'
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"

- name: Hash passwords from vault
  include_tasks: hash_passwords.yml
  no_log: true
  loop: "{{ authelia_users | dict2items }}"
  loop_control:
    index_var: index