---
- name: Copy additional files
  copy:
    src: "{{ item }}"
    dest: "{{ traefik_dir }}"
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: "0700"
  with_fileglob:
    - "{{ traefik_files_location }}"
  when: traefik_copy_extra_files
