---
- name: Hash password with Authelia Docker container
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      docker run {{ traefik_authelia_hash_image }}\
       {{ traefik_authelia_hash_command }} --password {{ item.password }} |\
        cut -d ' ' -f2
  no_log: true
  delegate_to: "{{ traefik_authelia_hash_host }}" 
  register: hashed_pw
  changed_when: true

- name: Add password to the users_database
  ansible.builtin.blockinfile:
    block: "    password: {{ hashed_pw.stdout }}"
    insertafter: '^\s+{{ item.username }}:'
    path: "{{ traefik_authelia_dir }}/users_database.yml"
    marker: "# {mark} ANSIBLE HASHED PASSWORD FOR {{ item.username }}"
