- name: Check for rollback
  ansible.builtin.command:
    cmd: "docker service inspect item.name --format '{{ '{{' }} .UpdateStatus.State {{ '}}' }}'"
  register: inspect
  failed_when: ("rollback" in inspect.stdout)
  changed_when: false
- name: Check for errors
  ansible.builtin.shell:
    cmd: "docker service ps {{ item.name }} --format '{{ '{{' }} .CurrentState {{ '}}' }}' | awk '{print $1}'| grep Running | wc -l"
  register: inspect
  changed_when: false
- name: Debugging hint
  ansible.builtin.debug:
    msg: "Service {{ item.name }} is failing. You can check the logs with 'docker service logs {{ item.name }}'"
  when: (inspect.stdout|int != item.replicas)
  failed_when: (inspect.stdout|int != item.replicas)
- name: Ensure all services are reachable
  ansible.builtin.uri:
    url: "{{ item.url }}"
    return_content: "{{ item.content | default(omit) }}"
    force: true
  when: (item.url is defined)
  register: http_response
- name: Fail playbook on non-200 HTTP status code
  fail:
    msg: "HTTP status code is not 200 OK. Actual status code: {{ http_response.status }}"
  when: http_response.status != 200
