---
# tasks file for traefik
- name: Ensures traefik dir exists
  file:
    path: "{{ traefik_dir }}"
    state: directory
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: 0700
  notify: "restart traefik"

- name: Ensures acme.json file exists
  file:
    path: "{{ traefik_dir }}/acme.json"
    state: touch
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: 0600

- name: Include ACME Cloudflare Docker secrets
  include_tasks: cloudflare-secrets.yml
  when: traefik_cloudflare

- name: Ensures traefiks rules directory exists
  file:
    path: "{{ traefik_dir }}/rules"
    state: directory
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: 0700

- name: Copy rules files
  copy:
    src: "{{ item }}"
    dest: "{{ traefik_dir }}/rules"
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: 0700
  with_fileglob:
    - "files/rules/*"

- name: Adding docker-compose file
  copy:
    src: "files/{{ traefik_compose_file }}"
    dest: "{{ traefik_dir }}/{{ traefik_compose_file }}"
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: 0700
  notify: "restart traefik"

- name: Start docker-compose
  community.docker.docker_compose:
    project_src: "{{ traefik_dir }}"
  register: output
