---
- name: Make sure docker is running
  ansible.builtin.systemd_service:
    name: docker
    state: started

- name: Init a new swarm with default parameters
  community.docker.docker_swarm:
    state: present

- name: Ensures traefik dir exists
  ansible.builtin.file:
    path: "{{ traefik_dir }}"
    state: directory
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: '0700'

- name: Ensures acme.json file exists
  ansible.builtin.file:
    path: "{{ traefik_dir }}/acme.json"
    state: touch
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: '0600'

- name: Include Docker secrets creation
  ansible.builtin.include_tasks: secrets.yml
  when: traefik_cloudflare
  loop: "{{ traefik_containers }}"
  loop_control:
    loop_var: service

- name: Include traefik rules validation
  ansible.builtin.include_tasks: validate.yml
  when: traefik_copy_rules

# authelia starting point in b5a0d414fbb787d52bd23e14e2746e88fbee6bac

- name: Create Docker networks
  community.docker.docker_network:
    name: "{{ item.key }}"
    internal: "{{ item.value.internal }}"
    driver: "{{ item.value.driver }}"
  loop: "{{ traefik_networks | dict2items }}"

- name: Create Docker Swarm services
  community.docker.docker_swarm_service:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    replicas: "{{ item.replicas }}"
    hostname: "{{ item.hostname | default(omit) }}"
    mounts: "{{ item.mounts | default(omit) }}"
    publish: "{{ item.publish | default(omit) }}"
    env: "{{ item.environment | default(omit) }}"
    networks: "{{ item.networks }}"
    args: "{{ item.command | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    secrets: "{{ item.secrets | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    cap_add: "{{ item.cap_add | default(omit) }}"
  no_log: "{{ traefik_no_service_log}}"
  loop:
    "{{ traefik_containers }}"
  notify: service_changed
