---
- name: Create secret
  community.docker.docker_secret:
    data: "{{ traefik_docker_secrets }} | selectattr({{ secret.secret_name }}, 'definded')"
    name: "{{ secret.secret_name }}"
    state: present
  ignore_errors: true
  register: create_secret
  no_log: true

- name: Update secret
  when: create_secret.failed
  block:
    - name: Remove current secret from service
      command: "docker service update
        --secret-rm {{ secret.secret_name }}
         {{ service.name }}"
    - name: Delete old secret
      community.docker.docker_secret:
        name: "{{ secret.secret_name }}"
        state: absent
    - name: Create new secret
      community.docker.docker_secret:
        name: "{{ secret.secret_name }}"
        data: "{{ traefik_docker_secrets }} | 
          selectattr({{ secret.secret_name }}, 'definded')"
        state: present
      no_log: true
    - name: Add new secret to service
      command: "docker service update
        --secret-add source={{ secret.secret_name }},target={{ secret.secret_name }}
         {{ service.name }}"
