---
# Kept for when there is a v3 json schema
- name: Find treafik container in traefik_containers "traefik"
  set_fact:
    traefik_definition: "{{ traefik_containers | selectattr('image', 'match', 'traefik:') | first }}"

- name: Split string after ":" to get the traefik image version
  set_fact:
    traefik_version: "{{ traefik_definition.image.split(':')[1] | regex_replace('^v', '') | default('') }}"

- name: Validate if traefik version < v3
  when: traefik_version is version('3.0.0', '<')
  block:
    - name: Run a simple command (argv)
      community.docker.docker_container_exec:
        container: ghcr.io/otto-de/traefik-config-validator
        argv:
          - "-cfgdir"
          - "/traefik"
      delegate_to: localhost
      register: validation
      become: false
    
    - name: Fail when validation failed
      ansible.builtin.fail:
        msg: |
          Validation failed!
          {{ validation.strerr_lines }}
      when: validation.rc != 0

- name: Copy rules files
  copy:
    src: "{{ item }}"
    dest: "{{ traefik_dir }}/rules"
    owner: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    mode: '0700'
  with_fileglob:
    - "{{ traefik_rules_location }}/*.yml"
