---
# handlers file for traefik
- name: Wait for the service to come up
  ansible.builtin.pause:
    minutes: 1
  listen: service_changed

- name: Healthcheck
  ansible.builtin.include_tasks: tasks/healthcheck.yml
  loop: "{{ traefik_containers }}"
  listen: service_changed
